// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp7hI2SWGUvy5Sa_cDkP75YL5uMsN7bBs',
    appId: '1:372211948363:web:72b46e23dc5e33a08aa6ce',
    messagingSenderId: '372211948363',
    projectId: 'chat-2-bcc87',
    authDomain: 'chat-2-bcc87.firebaseapp.com',
    storageBucket: 'chat-2-bcc87.appspot.com',
    measurementId: 'G-DHREJYP939',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-MztGeU0N-d_vHs3MADXFXgHR2upEtmU',
    appId: '1:372211948363:android:87fa6912fe56405f8aa6ce',
    messagingSenderId: '372211948363',
    projectId: 'chat-2-bcc87',
    storageBucket: 'chat-2-bcc87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnCzLUEI-EE70qM6HjPF-TuPKmr57O-A0',
    appId: '1:372211948363:ios:24a3c2522a2d0b7f8aa6ce',
    messagingSenderId: '372211948363',
    projectId: 'chat-2-bcc87',
    storageBucket: 'chat-2-bcc87.appspot.com',
    iosClientId:
        '372211948363-ou115e6md39d25l11jsfqcdd5g7rqm2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.muslim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnCzLUEI-EE70qM6HjPF-TuPKmr57O-A0',
    appId: '1:372211948363:ios:633c8bfb301911b88aa6ce',
    messagingSenderId: '372211948363',
    projectId: 'chat-2-bcc87',
    storageBucket: 'chat-2-bcc87.appspot.com',
    iosClientId:
        '372211948363-bc4mp9aj7bmqh5g6odq71r5s1jc24c2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.muslim.RunnerTests',
  );
}
